application: wavefiltre
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: main.py
  
- url: /assets
  static_dir: assets
 
- url: /static
  static_dir: static
  
- url: /
  static_files: index.html
  upload: index.html

- url: /argo.txt
  static_files: argo.txt
  upload: argo.txt
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
